const assert = require('assert')
let num = 12;

assert.equal(num, 10) // to test if function is running then it will throw in an err
console.log('hhaha')